workflowscommunity/workflowscommunity.github.io

page_systems.html

Perhaps we should say something about how entries in this curated list was chosen - in a sense to be more useful than a big list.

Link to More workflow systems

---

_data/events.yml

.. as it brings together many open source workflow developers in bioinformatics

Add BOSC conference

---

_data/events.yml

Ai ai, a bit late for that deadline for me.. but event valuable to list!

Add Sci-k 2022

---

_data/workflow_systems.yml

We would like to add the Apollo runtime system developed by the DPS group of the University of Innsbruck to the list of open-source workflow systems.

added the Apollo runtime system to the list

---

_data/events.yml

Add GCC2022 to events

---

_data/workflow_systems.yml

Taking advantage of 392d2f1c5b46f9ab3de057edd1fcde290243daa1

move metadata for aiida

---

_data/events.yml

https://nf-co.re/events/2022/hackathon-march-2022

Add March 2022 nf-core hackathon to events page

---

_data/workflow_systems.yml

Added the [StreamFlow](https://streamflow.di.unito.it/) WMS to the list of workflow systems.

Added StreamFlow to workflow systems

---

_data/workflow_systems.yml

More info at https://scipipe.org

Add SciPipe

---

_data/workflow_systems.yml

`.wci.yml` under PR https://github.com/Libensemble/libensemble/pull/804

Add libEnsemble

---

_jobs/ornl_computer_scientist.md
_jobs/ornl_scientific_software_engineer.md

My group is hiring! Two positions just opened: one for a Scientific Software Engineer and the other for a Computer Scientist. 
Both have a focus on scientific workflows, scientific data, data science, storage, and I/O.

2 job offers from the Worflow Systems Group@ORNL

---

_jobs/university_innsbruck_assistant_professor.md

Hi, we would like to add a job offer

added job assistant professor university of innsbruck

---

_data/workflow_systems.yml

https://github.com/icui/nnodes

Add nnodes

---

_jobs/naturemetrics_bioinformatics_pipeline_developer.md

Update to the logo to be compatible with the white background on the website.
Thanks.

update logo for NatureMetrics job post

---

_data/events.yml

Added a new entry to the events.yml file for the October 2022 HTCondor Week. The event regularly involves discussions of the HTCondor DAGMan as well as Pegasus WMS, along with a variety of other tools community used to maximize automated throughput.

Update events.yml with 2022 Autumn HTCondor meeting

---

_data/members.yml

Update my affiliation

---

_jobs/bsc_workflows_engineer.md

Hi, we have a position in my group at the BSC to work on our workflows & workflow manager (Autosubmit) and we would like help to advertise it to a wider audience.
Let me know if there's anything missing, it's my first PR for the job listings in the workflows community page.
Thanks!
Bruno

Add HPC workflows engineer job position at the BSC

---

_data/workflow_systems.yml

Hi! :wave: I'd like to add [WATTS](https://github.com/watts-dev/watts) to the list of workflow systems. This is a Python package that has been developed by myself and several colleagues at Argonne National Lab over the last year. I've already added a .wci.yml file to the main repo.

Add WATTS to list of workflow systems

---

_data/workflow_systems.yml

Hello,
I'd like to add [SmartSim](https://github.com/CrayLabs/SmartSim) to the list of workflow systems.  SmartSim is an open source workflow library actively developed by a Hewlett Packard Enterprise.  The ``.wci.yml`` has already been added to the SmartSim repository.  Thank you!

Add SmartSim to list of workflow systems

---

_data/workflow_systems.yml

This requires https://github.com/pyiron/pyiron_base/pull/1055 to be merged first.

Add pyiron

---

_data/events.yml

I essentially took on of the other events here as blueprint.

DOE cross facility workflows event

---

_data/events.yml

Add 2023 Nextflow-related events

Add Nextflow-related events

---

_data/events.yml

Adding the series tag so that links appear in the events page.

Update Nextflow-relaetd events in events.yml

---

_data/workflow_systems.yml

A workflow component with minimal dependencies.

Added mpi_list

---

_data/events.yml
contribute_events.html
index.html
page_events.html
search.json

- events: "short_name" is a better name than "series"
- events: show the date range if start_date != end_date
- add cwlcon2024 events (separate entries given the different types/locations and gaps in the schedule)

cwlcon2024

---

_data/workflow_systems.yml

Hello,
I'd like to add [DagOnStar](https://github.com/DagOnStar/dagonstar) to the list of workflow systems. The .wci.yml has already been added to the DagOnStar repository. Thank you!

Add DagOnStar to list of workflow systems

---

_data/workflow_systems.yml

Hi, here's a PR to add Cylc to your list of workflow systems, if that's deemed acceptable.
https://cylc.github.io/
Cylc is a general purpose, Open Source, workflow manager. It is actively developed, and written in Python.
It is used quite widely for weather, climate, other environmental prediction, and related workflows. Cylc is not specialized to those domains, but the way it handles cycling systems makes it very useful for them, and it provides powerful runtime intervention capabilities (e.g., to rerun past sub-graphs while the main flow front continues) for when things break in long-running systems.
(We haven't had much interaction with the wider workflows community to date, largely because cycling is our raison d'etre, which seems not to be such a thing for others.)
I'll post a Cylc …

Add Cylc to workflows list.

---

_talks/2025_04_16.html
page_talks.html

Add registration button to talk series page and talk page.
Takes you to a google form, so we can verify and add to zoom registration.

Add registration button

---

.github/workflows/workflow_systems.yml
.gitignore
_data/workflow_systems.yml
contribute_systems.html
scripts/github.html.in
scripts/gitlab.html.in
scripts/process_systems.py
scripts/pypi.html.in
scripts/requirements.txt

add gitlab and pypi as a source

---

scripts/process_systems.py

Improve https://github.com/workflowscommunity/workflowscommunity.github.io/pull/94 by using publish and update time from pypi.

extract publish and update time from pypi
